# Generated by Django 6.0.3 on 2026-06-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cookie_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookie',
            options={'permissions': [('can_publish_cookie', 'Может публиковать печенье')], 'verbose_name': 'Печенье', 'verbose_name_plural': 'Печенье'},
        ),
    ]
