# Generated by Django 6.0.3 on 2026-06-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cookie_author_comment_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookie',
            options={'verbose_name': 'Пищевая ценность', 'verbose_name_plural': 'Пищевая ценность'},
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='cookie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='shop.cookie', verbose_name='Печенье'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='proteins',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Белки'),
        ),
    ]
