# Generated by Django 6.0.3 on 2026-06-07 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cookie_options_alter_nutrition_calories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк')], max_length=10, verbose_name='Реакция')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата реакции')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='shop.comment', verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на комментарий',
                'verbose_name_plural': 'Реакции на комментарии',
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
