# Generated by Django 6.0.3 on 2026-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='status',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
