# Generated by Django 6.0.3 on 2026-05-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_tag_alter_cookie_status_cookie_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='cookie',
            options={'verbose_name': 'Печенье', 'verbose_name_plural': 'Печенье'},
        ),
        migrations.AlterModelOptions(
            name='nutrition',
            options={'verbose_name': 'Пищевая ценность', 'verbose_name_plural': 'Пищевая ценность'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
