# Generated by Django 6.0.3 on 2026-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_cookie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
